import type { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";

// Child components.
import NavigationBar from "@/components/frontPages/navigationBar";
import Footer from "@/components/frontPages/footer";
import BootstrapClient from "@/app/bootstrapClient";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className="container-fluid p-0 d-flex flex-column">
                <NavigationBar />
                <main className="flex-fill h-100">
                    {children}
                </main>
                <Footer />
                <BootstrapClient />
            </body>
        </html>
    );
}